

name: Compile CV LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile CV
        uses: xu-cheng/latex-action@4.0.0
        with:
          root_file: |
            cv.tex
